/**
${pojo.getClassJavaDoc(pojo.getDeclarationName()?replace(tablePrefix,"") + " generated by hbm2java", 0)}
 */
<#include "Ejb3TypeDeclaration.ftl"/>
${pojo.getClassModifiers()} ${pojo.getDeclarationType()} ${pojo.getDeclarationName()?replace(tablePrefix,"")} ${pojo.getExtendsDeclaration()} implements Serializable